spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

spotify:
  client-id: test-id
  client-secret: test-secret

jwt:
  secret: c2VjcmV0LWtleS1mb3ItdGVzdGluZy1wdXJwb3Nlcy1vbmx5LW5vdC1mb3ItcHJvZHVjdGlvbg==
  access-token-expiration: 3600
  refresh-token-expiration: 3600

mailgun:
  api-key: test
  domain: test
  from: test@test.com

tmap:
  api-key: test
kakao:
  restapi-key: test
kopis:
  api-key: test

oauth:
  kakao:
    client-id: test
    client-secret: test
    redirect-uri: test
  google:
    client-id: test
    client-secret: test
    redirect-uri: test

cloud:
  aws:
    s3:
      bucket: test-bucket
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    stack:
      auto: false